site_name: Convertlab 文档中心

site_url: http://api-docs.convertlab.com/

repo_url: https://github.com/xsio/open_api_docs

theme_dir: themes/mkdocs


copyright: Copyright &copy; 2017, Convertlab

extra_css: 
  - test/css/print.css
#   - test/css/reset.css
#   - test/css/screen.css
#   - test/css/style.css
#   - test/css/typography.css
extra_javascript:
  - test/swagger-ui.min.js

pages:
- OpenAPI V1:
  - '创建集成应用': 'index.md'
  - '获取身份权限': 'api/accesstoken.md'
  - '客户信息': 'api/customer.md'
  - '客户事件': 'api/customerevent.md'
  - '客户标签': 'api/tag.md'
  - '客户订单': 'api/deal.md'
- '网页埋点':
  - '设置埋点': 'track/index.md'
  - '客户自定义事件': 'track/customerevent.md'
  - '来源跟踪': 'track/sourcetracking.md'
# - 'TRY IT':
#   - 'TRY IT': 'test/index.md'
